Initialize Sentry
Pocket/proxy-server pull request #45
Opened 2021-01-08 01:00 UTC by mmiermans

## Goal

Insert purpose of pull request

## Todos:
- [ ] Outstanding todo
- [x] Completed todo

## Implementation Decisions

## All Submissions:

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

2021-01-21 01:12 UTC, bassrock requested changes
@mmiermans Can we pair on this? There's actually a much much easier approach you can take with the ECS task definition for using secrets.

Instead, there is an option called Secret Environment Variables that you can pass in the task definition and ECS will perform the secret decryption for you and inject the value as an environment variable only the task can see the value of.

https://aws.amazon.com/premiumsupport/knowledge-center/ecs-data-security-container-task/

2021-01-22 15:16 UTC, kkyeboah reviewed
Based on @bassrock's comment, there appears to be a simpler way to get secrets in ECS containers. Commenting to remove from queue.

2021-01-25 16:07 UTC, jpetto reviewed
commenting to remove from review queue. feel free to re-ping after addressing daniel's comment.

2021-01-26 15:35 UTC, bassrock submitted a review, later dismissed
👍 paired together. Looks great to me!

2021-01-26 18:08 UTC, bassrock reviewed
Just had one comment.

2021-01-26 18:08 UTC, bassrock commented on cloudformation/proxy-service.yaml
> -              - Effect: Allow
@mmiermans lets leave this in. If we remove it then we need to time deploys perfectly, but if we leave it we can deploy the code change at will.

2021-01-26 18:17 UTC, bassrock approved these changes

2021-01-26 20:52 UTC, merged